apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      securityContext:
          runAsUser: 2000
          runAsGroup: 3000
          fsGroup: 2000
      volumes:
      - name: sec-ctx-vol
        emptyDir: {}
      containers:
      - name: hello-world
        image: okteto.dev/hello-world:latest
        
        securityContext:
          runAsUser: 1000
        volumeMounts:
        -  name: sec-ctx-vol
           mountPath: /data/demo
        
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Hello > /data/demo/testfile"]
              
        
        #command: ["ls"]
        
        #args: 
        #- /bin/sh
        #- -c
        #-  echo Hi > /data/demo/testfile   
        #- ls 
    
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          periodSeconds: 5

        readinessProbe:
          exec:
            command:
            - cat
            - /data/demo/testfile
          periodSeconds: 5 

        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 5
          periodSeconds: 10

        ports:
        - containerPort: 8080
